import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/get_navigation/get_navigation.dart';

import 'package:xprintersdk/Model/printerbusinessmodel.dart';
import 'package:xprintersdk/xprintersdk.dart';

import 'orderjson.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _platformVersion = 'Unknown';
  final _xprintersdkPlugin = Xprintersdk();

  var ordermodeldata = {
    "id": null,
    "online_order_id": null,
    "service_charge": 0.0,
    "tips": 0.0,
    "order_id": null,
    "errorcode": 0,
    "barcode": "EPOS_1741239813063831",
    "local_id": 1,
    "tableUniqID": 1741239813063831,
    "selectDiscount": 0.0,
    "table_id": null,
    "order_type": "COLLECTION",
    "changeAmount": 0.0,
    "order_channel": "EPOS",
    "order_date": "2025-03-06 05:43:45",
    "requester_type": "PROVIDER",
    "requester_id": 0,
    "requester_uuid": 0,
    "shipping_address_id": 0,
    "requested_delivery_timestamp": "2025-03-06 05:43:45",
    "status": "PROCESSING",
    "net_amount": 5.75,
    "discounted_amount": 0.0,
    "delivery_charge": 0.0,
    "payable_amount": 5.75,
    "payment_type": "NOTPAY",
    "payment_id": 0,
    "prescriber_id": 0,
    "branch_id": 0,
    "comment": "",
    "created_at": "2025-03-06T05:43:45.740299",
    "updated_at": "2025-03-06T05:43:45.740632",
    "order_products": [
      {
        "id": 89365,
        "master_id": 0,
        "parent_id": null,
        "order_id": null,
        "product_id": null,
        "parent_product_id": null,
        "unit": 1,
        "net_amount": 1.5,
        "discountable_amount": null,
        "comment": null,
        "product": {
          "id": 89365,
          "sort_order": 0,
          "uuid": "banoful-butter-cookies-250g-hLG",
          "barcode": "8941114001519",
          "type": "ITEM",
          "short_name": "BANOFUL BUTTER COOKIES 250G",
          "description": "BANOFUL BUTTER COOKIES 250G",
          "status": 1,
          "discountable": 1.0,
          "creator_id": 1,
          "creator_uuid": "9c870ba8-9807-4ece-8f91-55f6754396e5",
          "property": {
            "expire_date": null,
            "product_group_sort": "1",
            "product_group": "",
            "platform": null,
            "unit_amount": "0",
            "master": "0",
            "epos_category": "bakery",
            "is_coupon": null,
            "category": "bakery",
            "featured": null,
            "unit_of_sale": "KG",
            "discount_type": null,
            "discount_value": null,
            "print_order": "10",
            "print_order_enable": "0",
            "purchase_price": null,
            "tare_weight": "0",
            "total_unit": null,
            "total_unit_price": null,
            "cost_price": null,
            "sale_price_without_tax": null,
            "sale_price_with_tax": null,
            "margin": null,
            "supplier": null,
            "orderCode": null,
            "sell_on_till": null,
            "unit_product_type": null,
            "unit_of_purchase": null,
            "available_to_butcher": "0",
          },
          "files": [],
        },
        "components": [],
        "priceEditManage": false,
        "priceEditComment": "",
        "property": null,
        "selectSubCategoryKey": "bakery",
        "selectMainCategoryKey": "",
        "offer": null,
        "bands": [],
      },
      {
        "id": 88127,
        "master_id": 0,
        "parent_id": null,
        "order_id": null,
        "product_id": null,
        "parent_product_id": null,
        "unit": 1,
        "net_amount": 1.0,
        "discountable_amount": null,
        "comment": null,
        "product": {
          "id": 88127,
          "sort_order": 0,
          "uuid": "azka-salted-biscuit-180g-sea",
          "barcode": "8827194382642",
          "type": "ITEM",
          "short_name": "AZKA SALTED BISCUIT 180G",
          "description": "AZKA SALTED BISCUIT 180G",
          "status": 1,
          "discountable": 1.0,
          "creator_id": 1,
          "creator_uuid": "9c870ba8-9807-4ece-8f91-55f6754396e5",
          "property": {
            "expire_date": null,
            "product_group_sort": "1",
            "product_group": "",
            "platform": null,
            "unit_amount": "0",
            "master": "0",
            "epos_category": "bakery",
            "is_coupon": null,
            "category": "bakery",
            "featured": null,
            "unit_of_sale": "KG",
            "discount_type": null,
            "discount_value": null,
            "print_order": "10",
            "print_order_enable": "0",
            "purchase_price": null,
            "tare_weight": "0",
            "total_unit": null,
            "total_unit_price": null,
            "cost_price": null,
            "sale_price_without_tax": null,
            "sale_price_with_tax": null,
            "margin": null,
            "supplier": null,
            "orderCode": null,
            "sell_on_till": null,
            "unit_product_type": null,
            "unit_of_purchase": null,
            "available_to_butcher": "0",
          },
          "files": [],
        },
        "components": [],
        "priceEditManage": false,
        "priceEditComment": "",
        "property": null,
        "selectSubCategoryKey": "bakery",
        "selectMainCategoryKey": "",
        "offer": null,
        "bands": [],
      },
      {
        "id": 90116,
        "master_id": 0,
        "parent_id": null,
        "order_id": null,
        "product_id": null,
        "parent_product_id": null,
        "unit": 1,
        "net_amount": 2.25,
        "discountable_amount": null,
        "comment": null,
        "product": {
          "id": 90116,
          "sort_order": 0,
          "uuid": "akij-rice-ball-350g-inx",
          "barcode": "8941174031174",
          "type": "ITEM",
          "short_name": "AKIJ RICE BALL 350G",
          "description": "AKIJ RICE BALL 350G",
          "status": 1,
          "discountable": 1.0,
          "creator_id": 1,
          "creator_uuid": "9c870ba8-9807-4ece-8f91-55f6754396e5",
          "property": {
            "expire_date": null,
            "product_group_sort": "1",
            "product_group": "",
            "platform": null,
            "unit_amount": "0",
            "master": "0",
            "epos_category": "bakery",
            "is_coupon": null,
            "category": "bakery",
            "featured": null,
            "unit_of_sale": "KG",
            "discount_type": null,
            "discount_value": null,
            "print_order": "10",
            "print_order_enable": "0",
            "purchase_price": null,
            "tare_weight": "0",
            "total_unit": null,
            "total_unit_price": null,
            "cost_price": null,
            "sale_price_without_tax": null,
            "sale_price_with_tax": null,
            "margin": null,
            "supplier": null,
            "orderCode": null,
            "sell_on_till": null,
            "unit_product_type": null,
            "unit_of_purchase": null,
            "available_to_butcher": "0",
          },
          "files": [],
        },
        "components": [],
        "priceEditManage": false,
        "priceEditComment": "",
        "property": null,
        "selectSubCategoryKey": "bakery",
        "selectMainCategoryKey": "",
        "offer": null,
        "bands": [],
      },
      {
        "id": 89235,
        "master_id": 0,
        "parent_id": null,
        "order_id": null,
        "product_id": null,
        "parent_product_id": null,
        "unit": 1,
        "net_amount": 1.0,
        "discountable_amount": null,
        "comment": null,
        "product": {
          "id": 89235,
          "sort_order": 0,
          "uuid": "6-large-wholemeal-pitta-bread-XQH",
          "barcode": "5027255078702",
          "type": "ITEM",
          "short_name": "6 LARGE WHOLEMEAL PITTA BREAD ",
          "description": "6 LARGE WHOLEMEAL PITTA BREAD ",
          "status": 1,
          "discountable": 1.0,
          "creator_id": 1,
          "creator_uuid": "9c870ba8-9807-4ece-8f91-55f6754396e5",
          "property": {
            "expire_date": null,
            "product_group_sort": "1",
            "product_group": "",
            "platform": null,
            "unit_amount": "0",
            "master": "0",
            "epos_category": "bakery",
            "is_coupon": null,
            "category": "bakery",
            "featured": null,
            "unit_of_sale": "KG",
            "discount_type": null,
            "discount_value": null,
            "print_order": "10",
            "print_order_enable": "0",
            "purchase_price": null,
            "tare_weight": "0",
            "total_unit": null,
            "total_unit_price": null,
            "cost_price": null,
            "sale_price_without_tax": null,
            "sale_price_with_tax": null,
            "margin": null,
            "supplier": null,
            "orderCode": null,
            "sell_on_till": null,
            "unit_product_type": null,
            "unit_of_purchase": null,
            "available_to_butcher": "0",
          },
          "files": [],
        },
        "components": [],
        "priceEditManage": false,
        "priceEditComment": "",
        "property": null,
        "selectSubCategoryKey": "bakery",
        "selectMainCategoryKey": "",
        "offer": null,
        "bands": [],
      },
    ],
    "requester": null,
    "requester_guest": null,
    "shipping_address": {
      "id": null,
      "name": null,
      "type": null,
      "creator_type": null,
      "creator_id": null,
      "status": null,
      "created_at": null,
      "updated_at": null,
      "prop": null,
    },
    "waiterInfo": {
      "firstName": "Admin",
      "id": 0,
      "role": "ADMIN",
      "lastName": "",
      "phone": "admin",
      "password": "0000",
      "orderList": [],
      "loginTime": "2025-03-06 05:43:39",
      "logoutTime": "2025-03-06 05:43:39",
    },
    "order_files": [],
    "prescriber": null,
    "payment": null,
    "cash_entry": [],
    "branch": {"id": null, "name": "alislah", "value": null, "created_at": null, "updated_at": null, "property": null},
    "table": null,
    "property": {"comment": null, "requested_delivery_timestamp_type": "ASAP", "total_value_edit": null, "total_value_edit_note": null},
    "vat": 0.0,
    "totalvalueEdit": false,
    "totalValueEditcomment": "manager has edited price",
    "isDiscountGivenByAmount": false,
    "isDiscountGivenByUser": false,
    "waiterToEposSend": 1,
    "requestTime": 0,
    "entermanuallyRequestTime": false,
  };

  List<String> usbList = [];
  String selectUsb = "";

  labelPrinterInit() async {
    _xprintersdkPlugin.XprinterInitialization();
  }

  getUsbList() async {}

  Future xprinterConnectionCheck() async {
    var connected = await _xprintersdkPlugin.XPrinterConnect(printermodel);
    Get.showSnackbar(GetSnackBar(title: "Status", message: "printer connection status ${connected}"));
  }

  @override
  void initState() {
    getUsbList();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Plugin example app')),
        body: Column(
          children: [
            MaterialButton(
              onPressed: () {
                labelPrinterInit();
              },
              child: Text("Printer init"),
            ),
            MaterialButton(
              onPressed: () {
                xprinterConnectionCheck();
              },
              child: Text("Printer connect status"),
            ),
            MaterialButton(
              onPressed: () {
                xprinterConnectionCheck();
              },
              child: Text("Printer connect status"),
            ),
            MaterialButton(
              onPressed: () async {
                await _xprintersdkPlugin.bitmapSave(printermodel, ordermodeldata);
              },
              child: Text("Print image"),
            ),
          ],
        ),
      ),
    );
  }

  PrinterBusinessModel printermodel = PrinterBusinessModel.fromJson({
    "starter_group": true,
    "grocery_barcode_hight": 5,
    "grocery_barcode_width": 30,
    "grocery_barcode_text_show": true,
    "grocery_barcode_text_size": 10,
    "yuma_productid_length": 8,
    "business_email": "yuma@tech.com",
    "invoice_type": "GROCERY",
    "yuma_netamount_length": 5,
    "yuma_weight_length": 2,
    "yuma_totalprice_length": 5,
    "branchNameShow": true,
    "barcode_text_show": true,
    "barcode_text_size": 14,
    "order_group": false,
    "butcher_order_barcode_hight": 200,
    "butcher_order_barcode_width": 700,
    "barcode_dpi": 420,
    "singleProductBarcodeHight": 2,
    "butcherStickerFont": 1,
    "expireDateShow": true,
    "maxItemPrint": 1,
    "butcherPrintStyle": "1",
    "singleProductBarCodeWidth": 7,
    "price_per_weight_font": 22,
    "singleProductExpireFont": 15,
    "singleProductPriceFont": 13,
    "singleProductNameFont": 15,
    "singleProductPrintHight": 239,
    "business_name_font": 22,
    "expire_date_font": 20,
    "item_name_font": 30,
    "item_price_font": 24,
    "item_weight_font": 22,
    "barcode_hight": 7,
    "barcode_x": 10,
    "barcode_y": 10,
    "barcode_width": 24,
    "label_hight": 65,
    "label_width": 65,
    "orderChannel": "EPOS",
    "weightShow": false,
    "asapFontSize": 22,
    "highlighttextsize": 20,
    "weightMultiplyingPrice": true,
    "font_size": 22,
    "print_on_delivery": 1,
    "print_on_collection": 1,
    "print_on_table_order": 1,
    "print_on_tackway_order": 1,
    "auto_print": true,
    "show_order_no_invoice": true,
    "select_printer": "xprinter",
    "printer_connection": "usbconnection",
    "ip": "",
    "dpi": 203,
    "bluetooth_name": "",
    "bluetooth_address": "",
    "businessname": "AL - ISLAH CASH & CARRY",
    "businessphone": "01998821888",
    "businessaddress": "Argyll Avenue",
    "highlight": 40,
    "papersize": 80,
    "dynamicCollection": "Collection",
    "dynamicDelivery": "Delivery",
    "dynamicEatIn": "Eat In",
    "dynamicTakeaway": "Takeaway",
    "vat_number": null,
    "vat_company_name": null,
    "vat_note": null,
    "printer_style": "1",
    "header1Size": 22,
    "header2Size": 15,
    "header3Size": 17,
    "header4Size": 15,
    "footervatFontSize": 15,
    "serviceCharge": false,
    "xprinter_path": null,
    "propertyshop": false,
    "show_category_name": false,
  });
}
