var ordermodeldata = {
  "id": null,
  "online_order_id": null,
  "service_charge": 0.0,
  "tips": 0.0,
  "order_id": null,
  "errorcode": 0,
  "barcode": "EPOS_1738670106176025",
  "local_id": 1,
  "tableUniqID": 1738670106176025,
  "selectDiscount": 0.0,
  "table_id": null,
  "order_type": "COLLECTION",
  "changeAmount": 0.0,
  "order_channel": "EPOS",
  "order_date": "2025-02-04 18:48:44",
  "requester_type": "PROVIDER",
  "requester_id": 0,
  "requester_uuid": 0,
  "shipping_address_id": 0,
  "requested_delivery_timestamp": "2025-02-04 18:48:44",
  "status": "PROCESSING",
  "net_amount": 2.0,
  "discounted_amount": 0.0,
  "delivery_charge": 0.0,
  "payable_amount": 2.0,
  "payment_type": "NOTPAY",
  "payment_id": 0,
  "prescriber_id": 0,
  "branch_id": 0,
  "comment": "",
  "created_at": "2025-02-04T18:48:44.368",
  "updated_at": "2025-02-04T18:48:44.385",
  "order_products": [
    {
      "id": 87512,
      "master_id": 0,
      "parent_id": null,
      "order_id": null,
      "product_id": null,
      "parent_product_id": null,
      "unit": 3,
      "net_amount": 1.0,
      "discountable_amount": null,
      "comment": null,
      "product": {
        "id": 87512,
        "sort_order": 0,
        "uuid": "pran-frooto-mango-1l-IN7",
        "barcode": null,
        "type": "ITEM",
        "short_name": "PRAN FROOTO MANGO 1L",
        "description": "PRAN FROOTO MANGO 1L",
        "status": 1,
        "discountable": 1.0,
        "creator_id": 1,
        "creator_uuid": "9c870ba8-9807-4ece-8f91-55f6754396e5",
        "property": {
          "expire_date": null,
          "product_group": "",
          "platform": null,
          "unit_amount": "0",
          "master": "0",
          "epos_category": "drink",
          "is_coupon": null,
          "category": "drink",
          "featured": null,
          "unit_of_sale": "KG",
          "discount_type": null,
          "discount_value": null,
          "print_order": "10",
          "print_order_enable": "0",
          "purchase_price": null,
          "tare_weight": "0",
          "total_unit": null,
          "total_unit_price": null,
          "cost_price": null,
          "sale_price_without_tax": null,
          "sale_price_with_tax": null,
          "margin": null,
          "supplier": null,
          "orderCode": null,
          "sell_on_till": null,
          "unit_product_type": "",
          "unit_of_purchase": null,
          "available_to_butcher": "1"
        },
        "files": []
      },
      "components": [],
      "priceEditManage": false,
      "priceEditComment": "",
      "property": null,
      "selectSubCategoryKey": "",
      "selectMainCategoryKey": "",
      "offer": {
        "id": 1,
        "offer_id": 1,
        "product_id": 87512,
        "offer": {"id": 1, "title": "3 for 2", "type": "X_FOR_Y", "buy": 3, "for": 2.0, "start_from": null, "end_at": null, "status": 1}
      },
      "bands": []
    }
  ],
  "requester": null,
  "requester_guest": null,
  "shipping_address": {
    "id": null,
    "name": null,
    "type": null,
    "creator_type": null,
    "creator_id": null,
    "status": null,
    "created_at": null,
    "updated_at": null,
    "prop": null
  },
  "waiterInfo": {
    "firstName": "Admin",
    "id": 0,
    "role": "ADMIN",
    "lastName": "",
    "phone": "admin",
    "password": "0000",
    "orderList": [],
    "loginTime": "2025-02-04 17:55:35",
    "logoutTime": "2025-02-04 17:55:35"
  },
  "order_files": [],
  "prescriber": null,
  "payment": null,
  "cash_entry": [],
  "branch": {"id": null, "name": "alislah", "value": null, "created_at": null, "updated_at": null, "property": null},
  "table": null,
  "property": {"comment": null, "requested_delivery_timestamp_type": "ASAP", "total_value_edit": null, "total_value_edit_note": null},
  "vat": 0.0,
  "totalvalueEdit": false,
  "totalValueEditcomment": "manager has edited price",
  "isDiscountGivenByAmount": false,
  "isDiscountGivenByUser": false,
  "waiterToEposSend": 1,
  "requestTime": 0,
  "entermanuallyRequestTime": false
};

var butcherOrder = {
  "id": null,
  "online_order_id": null,
  "service_charge": 0,
  "tips": 0,
  "order_id": null,
  "errorcode": 0,
  "barcode": "BUTCHER_1738734135699219",
  "local_id": 0,
  "tableUniqID": 1738734135699219,
  "selectDiscount": 0,
  "table_id": null,
  "order_type": "COLLECTION",
  "changeAmount": 0,
  "order_channel": "BUTCHER",
  "order_date": "2025-02-05 11:42:33",
  "requester_type": "PROVIDER",
  "requester_id": 0,
  "requester_uuid": 0,
  "shipping_address_id": 0,
  "requested_delivery_timestamp": "2025-02-05 11:42:33",
  "status": "PROCESSING",
  "net_amount": 32,
  "discounted_amount": 3.2,
  "delivery_charge": 0,
  "payable_amount": 28.8,
  "payment_type": "NOTPAY",
  "payment_id": 0,
  "prescriber_id": 0,
  "branch_id": 0,
  "comment": "",
  "created_at": "2025-02-05T11:42:33.231636",
  "updated_at": "2025-02-05T11:42:33.232354",
  "order_products": [
    {
      "id": 2145,
      "master_id": 0,
      "parent_id": null,
      "order_id": null,
      "product_id": null,
      "parent_product_id": null,
      "unit": 1,
      "net_amount": 25,
      "discountable_amount": null,
      "comment": null,
      "product": {
        "id": 2145,
        "sort_order": 0,
        "uuid": "fa5e7740-e121-11ef-b9c0-69870d886415",
        "barcode": "1144772233",
        "type": "ITEM",
        "short_name": "test master 66",
        "description": null,
        "status": 1,
        "discountable": 1,
        "creator_id": 2,
        "creator_uuid": "9db2c1e2-8421-4150-bf1c-dfd673acf836",
        "property": {
          "expire_date": "25-03-31",
          "product_group": "",
          "platform": null,
          "unit_amount": "",
          "master": "1",
          "epos_category": "test-2",
          "is_coupon": null,
          "category": "test-2",
          "featured": "0",
          "unit_of_sale": "KG",
          "discount_type": null,
          "discount_value": null,
          "print_order": "10",
          "print_order_enable": "0",
          "purchase_price": null,
          "tare_weight": "0",
          "total_unit": null,
          "total_unit_price": null,
          "cost_price": null,
          "sale_price_without_tax": null,
          "sale_price_with_tax": null,
          "margin": null,
          "supplier": null,
          "orderCode": null,
          "sell_on_till": null,
          "unit_product_type": "WEIGHT",
          "unit_of_purchase": "KG",
          "available_to_butcher": "1"
        },
        "files": []
      },
      "components": [],
      "priceEditManage": false,
      "priceEditComment": "",
      "property": null,
      "selectSubCategoryKey": "test-2",
      "selectMainCategoryKey": "category",
      "offer": null,
      "bands": []
    },
    {
      "id": 2092,
      "master_id": 0,
      "parent_id": null,
      "order_id": null,
      "product_id": null,
      "parent_product_id": null,
      "unit": 1,
      "net_amount": 7,
      "discountable_amount": null,
      "comment": null,
      "product": {
        "id": 2092,
        "sort_order": 78,
        "uuid": "abel-pacheco-VHu",
        "barcode": "Quincy Gilliam",
        "type": "ITEM",
        "short_name": "Abel Pacheco",
        "description": "",
        "status": 1,
        "discountable": 1,
        "creator_id": 2,
        "creator_uuid": "9db2c1e2-8421-4150-bf1c-dfd673acf836",
        "property": {
          "expire_date": "31-Aug-1989",
          "product_group": "",
          "platform": null,
          "unit_amount": "",
          "master": "0",
          "epos_category": "test-2",
          "is_coupon": null,
          "category": "test-2",
          "featured": null,
          "unit_of_sale": "POUND",
          "discount_type": "Consequuntur officii",
          "discount_value": "Consequuntur officii",
          "print_order": "10",
          "print_order_enable": "0",
          "purchase_price": null,
          "tare_weight": "0",
          "total_unit": null,
          "total_unit_price": null,
          "cost_price": null,
          "sale_price_without_tax": null,
          "sale_price_with_tax": null,
          "margin": null,
          "supplier": null,
          "orderCode": null,
          "sell_on_till": null,
          "unit_product_type": "WEIGHT",
          "unit_of_purchase": "POUND",
          "available_to_butcher": "1"
        },
        "files": []
      },
      "components": [],
      "priceEditManage": false,
      "priceEditComment": "",
      "property": null,
      "selectSubCategoryKey": "test-2",
      "selectMainCategoryKey": "category",
      "offer": null,
      "bands": []
    },
    {
      "id": 2133,
      "master_id": 0,
      "parent_id": null,
      "order_id": null,
      "product_id": null,
      "parent_product_id": null,
      "unit": 1,
      "net_amount": 0,
      "discountable_amount": null,
      "comment": null,
      "product": {
        "id": 2133,
        "sort_order": 1,
        "uuid": "new-item-data-ln4",
        "barcode": null,
        "type": "ITEM",
        "short_name": "new item data",
        "description": null,
        "status": 1,
        "discountable": 1,
        "creator_id": 2,
        "creator_uuid": "9db2c1e2-8421-4150-bf1c-dfd673acf836",
        "property": {
          "expire_date": "25-01-10",
          "product_group": "",
          "platform": null,
          "unit_amount": "0",
          "master": "0",
          "epos_category": "test-2",
          "is_coupon": null,
          "category": "test-2",
          "featured": null,
          "unit_of_sale": "KG",
          "discount_type": null,
          "discount_value": null,
          "print_order": "10",
          "print_order_enable": "0",
          "purchase_price": null,
          "tare_weight": "0",
          "total_unit": null,
          "total_unit_price": null,
          "cost_price": null,
          "sale_price_without_tax": null,
          "sale_price_with_tax": null,
          "margin": "0",
          "supplier": null,
          "orderCode": null,
          "sell_on_till": "0",
          "unit_product_type": "STANDARD",
          "unit_of_purchase": "KG",
          "available_to_butcher": "1"
        },
        "files": []
      },
      "components": [],
      "priceEditManage": false,
      "priceEditComment": "",
      "property": null,
      "selectSubCategoryKey": "test-2",
      "selectMainCategoryKey": "category",
      "offer": null,
      "bands": []
    }
  ],
  "requester": null,
  "requester_guest": null,
  "shipping_address": {
    "id": null,
    "name": null,
    "type": null,
    "creator_type": null,
    "creator_id": null,
    "status": null,
    "created_at": null,
    "updated_at": null,
    "prop": null
  },
  "waiterInfo": {
    "firstName": "Admin",
    "id": 0,
    "role": "ADMIN",
    "lastName": "",
    "phone": "admin",
    "password": "0000",
    "orderList": [],
    "loginTime": "2025-02-05 11:42:20",
    "logoutTime": "2025-02-05 11:42:20"
  },
  "order_files": [],
  "prescriber": null,
  "payment": null,
  "cash_entry": [],
  "branch": {"id": null, "name": "branch-1", "value": null, "created_at": null, "updated_at": null, "property": null},
  "table": null,
  "property": {"comment": null, "requested_delivery_timestamp_type": "ASAP", "total_value_edit": null, "total_value_edit_note": null},
  "vat": 0,
  "totalvalueEdit": false,
  "totalValueEditcomment": "manager has edited price",
  "isDiscountGivenByAmount": false,
  "isDiscountGivenByUser": false,
  "waiterToEposSend": 0,
  "requestTime": 0,
  "entermanuallyRequestTime": false
};
